name: 'Build Python Package'
description: 'Sets up Python environment and builds package distributions'

inputs:
  version:
    description: "Release version"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build package distributions
      working-directory: ./src/python
      shell: bash
      run: python setup.py sdist bdist_wheel

    - name: Upload distribution artifacts
      working-directory: ./src/python
      uses: actions/upload-artifact@v4
      with:
        name: python-v${{ inputs.version }}
        path: dist/
    
    - name: Publish to PyPI
      working-directory: ./src/python
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/