name: "Bump Version"
description: "Detect semver bump type and update Config.ini"

inputs:
  bump-type:
    description: "Version bump type: patch, minor, major, beta"
    required: true

outputs:
  new-version:
    description: "The new version bumped from Config.ini"
    value: ${{ steps.bump.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Run bump_version.py
      id: bump
      shell: bash
      run: |
        # Run the version bump script with the specified bump type
        OUTPUT=$(python src/python/bump_version.py ${{ inputs.bump-type }})

        # Print all output for logging
        echo "$OUTPUT"

        # Extract the new version from the 'NewVersion:' line
        NEW_VERSION=$(echo "$OUTPUT" | grep "NewVersion:" | awk '{print $2}')

        # Set output for workflow
        echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

        # Optional log for clarity
        echo "Bumped version: $NEW_VERSION"
