name: Release Package

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Semver bump type [patch|minor|major|beta]"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - beta

  # Scheduled trigger: every Sunday 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

  # Trigger on changes to src/python or src/docker
  push:
    branches:
      - main
    paths:
      - 'src/python/**'
      - 'src/docker/**'

permissions:
  contents: write
  id-token: write
  packages: write
  discussions: write

jobs:
  test:
    uses: ./.github/workflows/test-package.yml

  bump:
    needs: test
    uses: ./.github/workflows/bump-version.yml
    with:
      bump-type: ${{ github.event.inputs.bump-type || 'patch' }}

  publish-pypi:
    needs: [bump, test]
    uses: ./.github/workflows/publish-pypi.yml
    secrets:
      pip_token: ${{ secrets.PYPI_API_TOKEN }}
    with:
      bump-type: ${{ github.event.inputs.bump-type || 'patch' }}

  publish-docker:
    needs: bump
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false

  release:
    needs: [publish-pypi, publish-docker, bump]
    uses: ./.github/workflows/release-tag.yml
    with:
      version: ${{ needs.bump.outputs.new-version }}
