name: Release Package

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Semver bump type [patch|minor|major|beta]"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - beta

  # Scheduled trigger: every Sunday 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

  # Trigger on changes to src/python or src/docker
  push:
    branches:
      - main
    paths:
      - 'src/python/**'
      - 'src/docker/**'

permissions:
  contents: write
  id-token: write
  packages: write
  discussions: write

jobs:
  test:
    uses: ./.github/workflows/test-package.yml

  bump:
    needs: test
    uses: ./.github/workflows/bump-version.yml
    with:
      bump-type: ${{ github.event.inputs.bump-type || 'patch' }}

  publish-pypi:
    needs: [bump, test]
    uses: ./.github/workflows/publish-pypi.yml
    secrets:
      pip_token: ${{ secrets.PYPI_API_TOKEN }}
    with:
      bump-type: ${{ github.event.inputs.bump-type || 'patch' }}

  publish-docker:
    needs: bump
    uses: ./.github/workflows/publish-docker.yml
    secrets: 
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}
      context: .
      dockerfile: ./src/docker/Dockerfile
      push: true

  release:
    needs: [publish-pypi, publish-docker, bump]
    uses: ./.github/workflows/release-tag.yml
    with:
      version: ${{ needs.bump.outputs.new-version }}
