name: Publish to PyPI

on:
  workflow_call:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build package distributions
        working-directory: ./src/python
        run: python setup.py sdist bdist_wheel

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-v${{ inputs.version }}
          path: ./src/python/dist/

      - name: Publish to PyPI
        working-directory: ./src/python
        run: python -m twine upload dist/* -u  __token__ -p ${{ secrets.PYPI_API_TOKEN }}
