name: Publish to PyPI

on:
  workflow_call:
    inputs:
      bump-type:
        description: "Version bump type: patch, minor, major, beta"
        required: true
        type: string
    
    secrets:
      pip_token:
        description: "Pip api tokens"
        required: true


jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Pypi-Release
    steps:
      - name: Update Install dependencies
        id: bump
        uses: ./.github/workflows/bump-version.yml
        with:
          bump-type: ${{ inputs.bump-type || 'patch' }}

      - name: Build package distributions
        working-directory: ./src/python
        run: python setup.py sdist bdist_wheel

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-v${{ steps.bump.outputs.new-version }} 
          path: ./src/python/dist/

      - name: Publish to PyPI
        working-directory: ./src/python
        run: python -m twine upload dist/* -u  __token__ -p ${{ secrets.pip_token }}
