name: Create Release

on:
  workflow_call:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write   # needed to push tags or publish release

jobs:
  Release-Tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed for pushing tags

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Git tag
        run: |
          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}

      - name: Generate release notes
        id: notes
        run: |
          # Get last tag
          last_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          echo "Last tag: $last_tag"

          if [ -n "$last_tag" ]; then
            body=$(git log $last_tag..HEAD --pretty=format:"- %s (%h)")
          else
            body=$(git log --pretty=format:"- %s (%h)")
          fi

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release via API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/releases \
            -f tag_name="v${{ inputs.version }}" \
            -f name="v${{ inputs.version }}" \
            -f body="${{ steps.notes.outputs.body }}" \
            -F draft=false \
            -F prerelease=false
