name: Test python package 

# Configures this workflow to run every time a change is pushed to the branch.
on:
  push:
    branches:
      - 'feature/*'
      - 'develop/*'
    paths:
      - 'src/docker/**'
      - 'src/python/**'

jobs:
  Test-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Test packages
        id: test
        uses: ./.github/actions/test-package
